config:
  prometheus_url: "http://localhost:9090"  # minikube
  docker_user: "host.minikube.internal:6789/clue"
  local_public_ip: "cluereg.local"
  local_port: 8888
  remote_platform_arch: "linux/arm64/v8"
  local_platform_arch: "linux/amd64"
  docker_registry_address: "host.minikube.internal:6789/clue"
  result_base_path: "results/"
  workloads: ["shaped"]